 export const lookup = [
    { match: 'monstera',     family: 'Araceae',       genus: 'Monstera',      origin: 'Central America',   toxicity: 'Toxic to pets'    },
    { match: 'epipremnum',   family: 'Araceae',       genus: 'Epipremnum',    origin: 'Southeast Asia',    toxicity: 'Toxic to pets'    },
    { match: 'spathiphyllum',family: 'Araceae',       genus: 'Spathiphyllum', origin: 'Tropical Americas', toxicity: 'Toxic to pets'    },
    { match: 'ficus',        family: 'Moraceae',      genus: 'Ficus',         origin: 'Tropical Asia',     toxicity: 'Toxic to pets'    },
    { match: 'zamioculcas',  family: 'Araceae',       genus: 'Zamioculcas',   origin: 'East Africa',       toxicity: 'Toxic to pets'    },
    { match: 'calathea',     family: 'Marantaceae',   genus: 'Calathea',      origin: 'South America',     toxicity: 'Non-toxic'        },
    { match: 'strelitzia',   family: 'Strelitziaceae',genus: 'Strelitzia',    origin: 'South Africa',      toxicity: 'Mildly toxic'     },
    { match: 'dracaena',     family: 'Asparagaceae',  genus: 'Dracaena',      origin: 'Africa & Asia',     toxicity: 'Toxic to pets'    },
    { match: 'aloe',         family: 'Asphodelaceae', genus: 'Aloe',          origin: 'Arabian Peninsula', toxicity: 'Toxic if ingested' },
    { match: 'echeveria',    family: 'Crassulaceae',  genus: 'Echeveria',     origin: 'Mexico',            toxicity: 'Non-toxic'        },
    { match: 'crassula',     family: 'Crassulaceae',  genus: 'Crassula',      origin: 'South Africa',      toxicity: 'Toxic to pets'    },
    { match: 'haworthia',    family: 'Asphodelaceae', genus: 'Haworthiopsis', origin: 'South Africa',      toxicity: 'Non-toxic'        },
    { match: 'ferocactus',   family: 'Cactaceae',     genus: 'Ferocactus',    origin: 'Southwestern USA',  toxicity: 'Non-toxic'        },
    { match: 'rosa',         family: 'Rosaceae',      genus: 'Rosa',          origin: 'Asia & Europe',     toxicity: 'Non-toxic'        },
    { match: 'helianthus',   family: 'Asteraceae',    genus: 'Helianthus',    origin: 'North America',     toxicity: 'Non-toxic'        },
    { match: 'lavandula',    family: 'Lamiaceae',     genus: 'Lavandula',     origin: 'Mediterranean',     toxicity: 'Mildly toxic'     },
    { match: 'ocimum',       family: 'Lamiaceae',     genus: 'Ocimum',        origin: 'Tropical Asia',     toxicity: 'Non-toxic'        },
    { match: 'mentha',       family: 'Lamiaceae',     genus: 'Mentha',        origin: 'Europe & Asia',     toxicity: 'Toxic to pets'    },
    { match: 'salvia',       family: 'Lamiaceae',     genus: 'Salvia',        origin: 'Mediterranean',     toxicity: 'Non-toxic'        },
    { match: 'thymus',       family: 'Lamiaceae',     genus: 'Thymus',        origin: 'Mediterranean',     toxicity: 'Non-toxic'        },
    { match: 'solanum',      family: 'Solanaceae',    genus: 'Solanum',       origin: 'South America',     toxicity: 'Toxic if unripe'  },
    { match: 'capsicum',     family: 'Solanaceae',    genus: 'Capsicum',      origin: 'Central America',   toxicity: 'Non-toxic'        },
    { match: 'lactuca',      family: 'Asteraceae',    genus: 'Lactuca',       origin: 'Eurasia',           toxicity: 'Non-toxic'        },
    { match: 'ipomoea',      family: 'Convolvulaceae',genus: 'Ipomoea',       origin: 'Southeast Asia',    toxicity: 'Non-toxic'        },
    { match: 'momordica',    family: 'Cucurbitaceae', genus: 'Momordica',     origin: 'Tropical Africa',   toxicity: 'Mildly toxic'     },
    { match: 'moringa',      family: 'Moringaceae',   genus: 'Moringa',       origin: 'South Asia',        toxicity: 'Non-toxic'        },
    { match: 'mangifera',    family: 'Anacardiaceae', genus: 'Mangifera',     origin: 'South Asia',        toxicity: 'Non-toxic'        },
    { match: 'musa',         family: 'Musaceae',      genus: 'Musa',          origin: 'Southeast Asia',    toxicity: 'Non-toxic'        },
    { match: 'citrus',       family: 'Rutaceae',      genus: 'Citrus',        origin: 'Southeast Asia',    toxicity: 'Non-toxic'        },
    { match: 'carica',       family: 'Caricaceae',    genus: 'Carica',        origin: 'Tropical America',  toxicity: 'Non-toxic'        },
    { match: 'psidium',      family: 'Myrtaceae',     genus: 'Psidium',       origin: 'Caribbean',         toxicity: 'Non-toxic'        },
    { match: 'jasminum',     family: 'Oleaceae',      genus: 'Jasminum',      origin: 'South Asia',        toxicity: 'Mildly toxic'     },
    { match: 'hibiscus',     family: 'Malvaceae',     genus: 'Hibiscus',      origin: 'East Asia',         toxicity: 'Non-toxic'        },
    { match: 'bougainvillea',family: 'Nyctaginaceae', genus: 'Bougainvillea', origin: 'South America',     toxicity: 'Mildly toxic'     },
    { match: 'phalaenopsis', family: 'Orchidaceae',   genus: 'Phalaenopsis',  origin: 'Southeast Asia',    toxicity: 'Non-toxic'        },
  ];